#Particle Editor Config
#Sat Aug 29 15:21:47 CEST 2026
BGColor=-4144960
DefaultFolder=H\:\\Work\\EclipseWorkspace\\ParticleEditor
DefaultFolderWorkingSet=C\:\\Users\\Andreas\\OneDrive\\Work\\Generals\\FX
FXListFile=C\:\\Work\\Generals\\Command & Conquer Generals - OFS 2.0\\Data\\INI\\FXList.ini
Fullscreen=true
GridColor=-8355712
GroundResolution=20.0
GroundSize=500.0
GroundTexture=ground.jpg
GroundType=1
ParticleSystemFile=C\:\\Work\\Generals\\Command & Conquer Generals - OFS 2.0\\Data\\INI\\ParticleSystem.ini
TextureFolder1=C\:\\Work\\Generals\\Command & Conquer Generals - OFS 2.0\\Art\\Textures
TextureFolder2=H\:\\Work\\EclipseWorkspace\\ParticleEditor\\textures
WindowHeight=1280
WindowWidth=1280
